### ISSUE TITLE
Wrong File Name

### ISSUE THREAD

**Issue by zanematthew** [WebDevStudios/WDS-WP-JSON-API-Connect#2]
In your [example code you specify](https://github.com/WebDevStudios/WDS-WP-JSON-API-Connect#wds-wp-json-api-connect-):

```
if ( ! class_exists( 'WDS_WP_JSON_API_Connect' ) ) {
    require_once( 'WDS_WP_JSON_API_Connect.php' );
}
```

Yet, there is not file named `WDS_WP_JSON_API_Connect.php`, it should be: `wds-wp-json-api-connect.php`.

Also I'd love to know if you are actively using this, if so on what projects.

**Comment by jtsternberg** [comment]
@zanematthew good catch, thank you. We were actively using it to push updates to another server (with WordPress) whenever a post was updated/added.
